# Generated by Django 5.2.8 on 2025-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_role_store_warehouse_remove_user_role_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('warehouse_admin', 'Warehouse Admin'), ('store_manager', 'Store Manager'), ('warehouse_manager', 'Warehouse Manager')], default='store_manager', help_text='The main role for permission checks.', max_length=20),
        ),
    ]
