# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user_primary_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfulfillment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered to Warehouse'), ('out_of_stock', 'Out of Stock'), ('ready_to_ship', 'Ready to Ship')], default='pending', max_length=20),
        ),
    ]
