# Generated by Django 5.2.8 on 2025-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_orderfulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfulfillment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered to Warehouse'), ('out_of_stock', 'Out of Stock'), ('ready_to_ship', 'Ready to Ship'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
