# Generated by Django 5.2.8 on 2025-11-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
