# Generated by Django 5.2.8 on 2025-11-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_user_profile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwarehouserole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userwarehouserole',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.store'),
        ),
        migrations.AlterUniqueTogether(
            name='userwarehouserole',
            unique_together={('user', 'warehouse', 'role', 'store')},
        ),
    ]
